/*
 * This source file was generated by the Gradle 'init' task
 */
package math.sample;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println("2 + 3 = " + MathOps.add(2, 3));
        System.out.println("5 - 2 = " + MathOps.subtract(5, 2));
        System.out.println("4 * 3 = " + MathOps.multiply(4, 3));
        System.out.println("8 / 2 = " + MathOps.divide(8, 2));
    }
}
